story/urls.py
from django.urls import path

from . import views

app_name = 'story9'

urlpatterns = [
    path('login/', views.userLogin, name='userLogin'),
    path('register/', views.register, name='register'),
    path('', views.homepage, name='homepage'),
    path('logout/', views.userLogout, name='userLogout'),
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story.urls')),
]

story/models.py
from django.db import models
from django.contrib.auth.models import User

# class UserModel(models.Model):
# 	user = models.OneToOneField(User, on_delete=models.CASCADE)
# 	username = models.CharField(max_length=100)
# 	email = models.CharField(max_length=100, null=True)
# 	password1 = models.CharField(max_length=200)

story/forms.py
from django import forms
from django.contrib.auth.models import User
# from .models import UserModel
from django.db import models

class UserRegisterForm(forms.ModelForm):
	
	class Meta:
		model = User
		fields = ['username', 'email','password']
		widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'email': forms.TextInput(attrs={'placeholder': 'Email', 'required': True}),
            'password': forms.PasswordInput(attrs={'placeholder': 'Password'}),
        }

story/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


def register(request):
	if request.method == 'POST' :
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			email = form.cleaned_data.get('email')
			password = form.cleaned_data.get('password')
			User.objects.create_user(username, email,password)
			# messages.success(request, f'Your account has been created! You are now able to log in')
			return redirect('story9:userLogin')
	else :
		form = UserRegisterForm()
	return render(request, 'story9/register.html', {'form' : form})


def userLogin(request):
	if request.method == 'POST' :
		username = request.POST['username']
		password = request.POST['password1']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request,user)
			return redirect('story9:homepage')
		else:
			messages.error(request, f'invalid username or password')
	elif request.user.is_authenticated:
		return redirect('story9:homepage')
	return render(request, 'story9/login.html')

def userLogout(request):
	logout(request)
	return redirect('story9:userLogin')

def homepage(request):
	if request.user.is_authenticated :
		user = request.user.username
		return render(request, 'story9/homepage.html', {'name': user, 'log': 1})
	return render(request, 'story9/homepage.html')

story/templates/story9/homepage.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'story9/home.css' %}">
</head>
<body>
	<header>
		<div class="logo">
			<img src="{% static 'story9/images/logo.png' %}">
		</div>
		<div class="links">
			{% if log %}
			<a href="{% url 'story9:userLogout' %}">Logout</a>
			{% else %}
			<a href="{% url 'story9:userLogin' %}">Login</a>
			{% endif %}
		</div>

	</header>
	<section class="main">
		{% if log %}
		<h1>Hello, {{ name }}.</h1>
		<p>Mau mendengarkan lagu apa hari ini?</p>
		{% endif %}


		<div class="songs">
			<div class="card"><a href="https://www.youtube.com/watch?v=_8G4oaOxyxk"><p>Troye Sivan - Wild</p></a></div>
			<div class="card"><a href="https://www.youtube.com/watch?v=8PTDv_szmL0"><p>Bruno Mars - Nothin' On You</p></a></div>
			{% if log %}
				<div class="card log"><a href="https://www.youtube.com/watch?v=Jtauh8GcxBY"><p>Lewis Capaldi - Before You Go</p></a></div>
				<div class="card log"><a href="https://www.youtube.com/watch?v=oljXXw0wgmg"><p>Alessia Cara - Out of Love</p></a></div>
			{% else %}
				<p class="pLog"><a href="{% url 'story9:userLogin' %}">Login</a> untuk melihat lebih banyak lagu</p>
			{% endif %}
		</div>
	</section>
	
</body>
</html>

story/templates/story9/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	 <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<title>Login Page</title>
	<link rel="stylesheet" type="text/css" href="{% static 'story9/login.css' %}">

</head>
<body>

	<section class="main">
		<div class="row">
			<div class="col col-10 offset-1 col-md-8 offset-md-2 col-lg-4 offset-lg-4">
				<div class="card">
					<div class="forms">
						<h1>Log In Akun</h1>
						{% csrf_token %}
						<form method="POST">
							{% csrf_token %}
							<input type="text" name="username" placeholder="Username">
							<br>
							<input type="password" name="password1" placeholder="Password">
							<div class="button"><button type="submit">Login</button></div>
						</form>
						{% if messages %}
					        {% for message in messages %}
					        	<p style="margin-top: 10px;">{{ message }}</p>
					        {% endfor %}
					    {% endif %}	
					</div>
					<div class="regist">
				    	<p>Belum punya akun? <a href="{% url 'story9:register' %}">Register</a> sekarang.</p>
				    </div>
				</div>		
			</div>
		</div>
		
	</section>

	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

story/templates/story9/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	 <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<title>Register Page</title>
	<link rel="stylesheet" type="text/css" href="{% static 'story9/login.css' %}">
</head>
<body>

	<section class="main">
		<div class="row">
			<div class="col col-10 offset-1 col-md-8 offset-md-2 col-lg-4 offset-lg-4">
				<div class="card">
					<div class="forms">
						<h1>Buat Akun Baru</h1>
						<form method="POST">
							{% csrf_token %}
							{{ form.username }}
							{{ form.email }}
							{{ form.password }}
							<div class="button"><button type="submit">Register</button></div>
						</form>
						{% if messages %}
					        {% for message in messages %}
					        	<p style="margin-top: 10px;">{{ message }}</p>
					        {% endfor %}
					    {% endif %}
					</div>
					<div class="regist">
				    	<p>Sudah punya akun? <a href="{% url 'story9:userLogin' %}">Login</a> sekarang.</p>
				    </div>
				</div>
			</div>
		</div>
	</section>

	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>